DROP TABLE IF EXISTS stocks;
DROP TABLE IF EXISTS transactions;
DROP TABLE IF EXISTS users;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  cash NUMERIC NOT NULL DEFAULT 10000.00
);

CREATE TABLE stocks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stk_id INTEGER IDENTITY(0,1),
  sym TEXT NOT NULL,
  nm TEXT NOT NULL,
  prc NUMERIC NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(stk_id) REFERENCES user(id)
);

CREATE TABLE transactions (
  stk_id INTEGER IDENTITY(0,1),
  symbol TEXT NOT NULL,
  price NUMERIC NOT NULL,
  shares NUMERIC NOT NULL,
  date TEXT,
  FOREIGN KEY(stk_id) REFERENCES user(id)
);
