DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS stocks;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  cash NUMERIC NOT NULL DEFAULT 10000.00
);

CREATE TABLE stocks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  stk_id INTEGER NOT NULL,
  sym TEXT NOT NULL,
  nm TEXT NOT NULL,
  prc NUMERIC NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(stk_id) REFERENCES user(id)
);

